In [ ]:
import numpy as np

data = np.random.randint(5, 3)
print(data) 


[[0.35178864 0.06599381 0.33381295]
 [0.96747792 0.67859364 0.95506691]
 [0.62139679 0.49910195 0.02469928]
 [0.08490063 0.11349054 0.55320071]
 [0.4310686  0.80087573 0.3853772 ]]
